trainer:
  target: trainers.ldm_trainer.LDMTrainer
  # ckpt_path: "checkpoints/50000"
  batch_size: 768
  num_workers: 2
  learning_rate: 1e-5
  num_iters: 500000
  val_every: 500
  num_val_iters: 50

  save_every: 10000

  use_wandb: true
  wandb_entity:
  wandb_project:
data:
  target: data.CIFAR10
dit:
  in_channels: 3
  num_channels: 384
  depth: 12
  num_heads: 6
  patch_size:
    - 1
    - 2
    - 2
  use_rope: true
  rope_ndim: 2
  mlp_ratio: 4.0
  t_dim: 256
  num_classes: 10
